apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-agent-sa
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sre-agent-readonly
rules:
  - apiGroups: [""]
    resources: ["pods", "events", "namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sre-agent-readonly-binding
subjects:
  - kind: ServiceAccount
    name: sre-agent-sa
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: sre-agent-readonly
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-agent
  namespace: monitoring
  labels:
    app: sre-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-agent
  template:
    metadata:
      labels:
        app: sre-agent
    spec:
      serviceAccountName: sre-agent-sa
      containers:
        - name: agent
          image: ghcr.io/clementtrecourt/sre-agent:latest
          imagePullPolicy: Always
          env:
            - name: OLLAMA_URL
              value: "http://ollama.ai.svc.cluster.local:11434/api/generate"
            - name: MODEL_NAME
              value: "qwen2.5-coder:1.5b"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sre-agent-secrets
                  key: GITHUB_TOKEN
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
