apiVersion: v1
kind: Service
metadata:
  name: sample-ai-service
  namespace: ai
  labels:
    app: sample-ai-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: sample-ai-service
