apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: quay.io/janus-idp/backstage-showcase:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--config"
            - "app-config.yaml"
            - "--config"
            - "app-config.production.yaml"
          ports:
            - containerPort: 7007
              name: http
          env:
            - name: APP_CONFIG_app_baseUrl
              value: http://backstage.192.168.1.50.nip.io
            - name: APP_CONFIG_backend_baseUrl
              value: http://backstage.192.168.1.50.nip.io
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backstage-secrets
                  key: GITHUB_TOKEN
          volumeMounts:
            - name: config-volume
              mountPath: /opt/app-root/src/app-config.production.yaml
              subPath: app-config.production.yaml
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 7007
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: backstage-config
---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
spec:
  ports:
    - port: 7007
      targetPort: 7007
      name: http
  selector:
    app: backstage
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage
  namespace: backstage
spec:
  ingressClassName: nginx
  rules:
    - host: backstage.192.168.1.50.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backstage
                port:
                  number: 7007
